server.port=8081
spring.application.name=ms-gestion-academica

# Conexión a la base de datos de Docker (admin/admin123)
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_academica
spring.datasource.username=admin
spring.datasource.password=admin123

# JPA y Hibernate (Crea las tablas automáticamente al iniciar)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true